name: Destroy PR deployment
on:
  pull_request:
    types: [ closed ]

jobs:
  destroy-pr-deployment:
    runs-on: ubuntu-latest
    environment: dev
    env:
      WORKSPACE: pr-${{ github.event.pull_request.number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install invoke
        run: pip install invoke

      - name: Config Terraform plugin cache
        run: |
          echo 'plugin_cache_dir="$HOME/.terraform.d/plugin-cache"' >~/.terraformrc
          mkdir --parents ~/.terraform.d/plugin-cache

      - name: Cache Terraform
        uses: actions/cache@v3
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: ${{ runner.os }}-terraform-

      - name: Deploy PR - init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: invoke init

      - name: Deploy PR - destroy
        uses: nick-fields/retry@v2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          timeout_minutes: 10
          max_attempts: 2
          command: invoke destroy --no-dryrun
